### ISSUE TITLE
Intel Realsense Full Hand Tracking and Gesture Recognition SDK

### ISSUE THREAD

**Issue by Crystal2333** [ReiiYuki/Intel-Realsense-Hand-Toolkit-Unity#1]
Hi! Could you tell me where can I download the prerequisite "Intel Realsense Full Hand Tracking and Gesture Recognition SDK"? It's not provided in the latest librealsense.
Thank you!

**Comment by ReiiYuki** [comment]
Hi!
You can download it from the following link
https://software.intel.com/en-us/realsense-sdk-windows-eol

Thank you for notice !
