### ISSUE TITLE
R200 STATUS_ITEM_UNAVAILABLE

### ISSUE THREAD

**Issue by leungzengzeng** [ReiiYuki/Intel-Realsense-Hand-Toolkit-Unity#3]
Unity5.65 R200 
`public void StartDevice()
    {
        if (senseManager.Init() == Status.STATUS_NO_ERROR)
        {
            Debug.Log(TAG + "Initialization Successful!");
            isStart = true;
        }
        else
            throw new System.Exception("Initialization Failed!");
    }`

senseManager.Init() STATUS_ITEM_UNAVAILABLE
r2 support r200,"Full Hand Tracking and Gesture Recognition SDK" belong to r3

**Comment by leungzengzeng** [comment]
> Unity5.65 R200
> `public void StartDevice() { if (senseManager.Init() == Status.STATUS_NO_ERROR) { Debug.Log(TAG + "Initialization Successful!"); isStart = true; } else throw new System.Exception("Initialization Failed!"); }`
> 
> senseManager.Init() STATUS_ITEM_UNAVAILABLE

r2 support r200,"Full Hand Tracking and Gesture Recognition SDK" belong to r3

**Comment by ReiiYuki** [comment]
Oh! That's my mistake. I'm sorry about that.

I checked the document `Full Hand Tracking and Gesture Recognition SDK` is belonged to R3 only.

Thanks for notice.

I will correct README.

**Comment by ReiiYuki** [comment]
I'm corrected the document!

So I'm closing the issue.

Feel free to open it again if you have some question. 

Thanks 😄
