### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by bakalarczuk** [ReiiYuki/Intel-Realsense-Hand-Toolkit-Unity#7]
Hi, is it will work on mobiles?

**Comment by ReiiYuki** [comment]
I haven't test this on mobile yet. BTW if SDK is supported on mobile device, it's sure that this toolkit is supported on mobile device too.

**Comment by bakalarczuk** [comment]
OK. I'll try it on mobile in free time.

**Comment by ReiiYuki** [comment]
Thanks ! I hope it work :smile:
